version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "epal_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"